name: Deploy

on:
  push:
    branches:
      - main

env:
  AWS_ACCOUNT_ID: 590184101838
  AWS_REGION: us-east-1
  AWS_APP: stevezelek-com
  NODE_VERSION: 16
  BUILD_DIR: public/
  CLOUDFLARE_ZONE: c272b1a950675498138a374bcbf3fe0f

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache NPM
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install
        run: npm ci

  deploy-app:
    needs: [install]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache NPM
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build:app
        timeout-minutes: 5
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_APP }}-github-role
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: 'no'
      - name: Deploy Build
        run: |
          cd ${{ env.BUILD_DIR }}
          aws s3 cp . s3://${{ env.AWS_APP }} --recursive
      - name: Purge Cloudflare Cache
        run: |
          curl -fsSL "https://api.cloudflare.com/client/v4/zones/${{ env.CLOUDFLARE_ZONE }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything": true}' \
            --fail --show-error
        shell: bash
