name: Refresh GitHub Contribution Data

on:
  workflow_dispatch:
  schedule:
    # (see https://crontab.guru) -> “At 03:00 AM UTC every day.”
    - cron: '0 3 * * *'

jobs:
  refresh_github:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache NPM
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Reload data
        run: node github.mjs
        env:
          SAFE_TOKEN: ${{ secrets.SAFE_TOKEN }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCS_SA_KEY }}

      - name: Setup gcloud and gsutil
        uses: google-github-actions/setup-gcloud@v0

      - name: Deploy to GCP
        run: |
          gsutil -m cp "assets/github.json" gs://www.stevezelek.com/assets

      - name: Clear GCP Cache
        run: gcloud compute url-maps invalidate-cdn-cache ${{ secrets.GCS_LB }} --path "/assets/github.json" --async
